import type { Metadata } from "next";

const items = [
  ["Logitech Wave Keys", "https://amzn.to/4ttElSo"], ["VAYDEER wrist rest", "https://amzn.to/4cKtL3y"], ["EKO Fandy mini bin", "https://www.amazon.com/dp/B0C73F1KB1?tag=gonzalotech-20"], ["Soundcore P40i", "https://www.amazon.com/dp/B0CQXM1FXT?tag=gonzalotech-20"], ["Amazon Basics ergonomic mouse pad", "https://www.amazon.com/dp/B06X3W3TM4?tag=gonzalotech-20"], ["cinnkeyi PC speakers", "https://www.amazon.com/dp/B0DYDPMWGB?tag=gonzalotech-20"], ["Highwings USB-C to HDMI adapter", "https://www.amazon.com/dp/B08GC1K9TF?tag=gonzalotech-20"], ["Sceptre 27-inch curved monitor", "https://www.amazon.com/dp/B0D2JM3NQG?tag=gonzalotech-20"], ["DIMONCOAT phone stand", "https://www.amazon.com/dp/B0C37P1YXH?tag=gonzalotech-20"], ["iPad Air 13 keyboard case", "https://www.amazon.com/dp/B0F489SNSL?tag=gonzalotech-20"], ["PANPEO right-angle HDMI adapters", "https://www.amazon.com/dp/B0F18XT8KP?tag=gonzalotech-20"], ["RedLemon L-shaped standing desk", "https://www.amazon.com/dp/B0DZC9N816?tag=gonzalotech-20"], ["Addtam power strip", "https://www.amazon.com/dp/B0GS5BWWVM?tag=gonzalotech-20"], ["K&F CONCEPT phone tripod", "https://www.amazon.com/dp/B0FWBHDJMM?tag=gonzalotech-20"], ["JSADZKJ C8 to C7 adapter", "https://www.amazon.com/dp/B0CSW35Z2W?tag=gonzalotech-20"], ["MOUNT PRO laptop arm", "https://www.amazon.com/dp/B0C65LM31H?tag=gonzalotech-20"], ["DYSANKY insulated water bottle", "https://www.amazon.com/dp/B0DLCRD5GF?tag=gonzalotech-20"], ["EUCOS 62-inch phone tripod", "https://www.amazon.com/dp/B09XHZ8F7F?tag=gonzalotech-20"],
] as const;

export const metadata: Metadata = { title: "Desk recommendations | Esteban Moreno Media", description: "Shared desk, recording and production-tool recommendations from Esteban and Gonzalo." };

export default function DeskRecommendations() { return <main className="bg-[#f6f1ea] px-5 py-16 text-[#101214]"><section className="mx-auto max-w-6xl"><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#9f3c27]">Shared recommendations</p><h1 className="mt-4 max-w-3xl font-serif text-5xl leading-none sm:text-7xl">Tools we actually keep around production and desk work.</h1><p className="mt-8 max-w-2xl text-lg leading-8">A shared list from Esteban and Gonzalo. Some links are Amazon affiliate links using Gonzalo&apos;s associate tag; a qualifying purchase may earn a commission at no extra cost to you.</p><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(([name, href]) => <article key={name} className="rounded-lg border border-[#ddd4c8] bg-[#fbf6ef] p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#9f3c27]">Amazon recommendation</p><h2 className="mt-5 font-serif text-2xl leading-tight">{name}</h2><a className="mt-8 inline-flex rounded border border-[#9f3c27] bg-[#9f3c27] px-4 py-3 text-sm font-semibold text-white" href={href} rel="sponsored noopener" target="_blank">View on Amazon ↗</a></article>)}</div></section></main>; }
