import type { MetadataRoute } from "next";

import { SITE_URL } from "@/lib/seo/business-info";

/**
 * `/robots.txt` — generated by Next.js from this file at build time.
 *
 * Policy:
 *  - Allow all user-agents to crawl every URL by default. The site has nothing
 *    to hide and we want maximum AI/SEO surface area.
 *  - Disallow `/api/*` — server route handlers (e.g. the contact form). They
 *    have no useful content for crawlers and we don't want them indexed as
 *    "thin pages" or accidentally surfacing in AI answers as endpoints.
 *  - Disallow `/_next/*` — Next.js internals. Most well-behaved crawlers skip
 *    these anyway, but being explicit costs nothing and avoids the rare bot
 *    that wastes budget on chunk files.
 *  - Reference the dynamic sitemap (generated by `app/sitemap.ts`) so crawlers
 *    discover the full URL set without guessing.
 *  - Set `host` to the canonical origin to nudge Google/Yandex toward the
 *    preferred host (matters more once the real domain is wired up).
 *
 * Note: there is no `noindex` here. Per-route `robots` metadata or HTTP
 * headers handle finer-grained signals — this file is the site-wide default.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/_next/"],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
