import type { MetadataRoute } from "next";

import { routing, type Locale } from "@/i18n/routing";
import { SITE_URL } from "@/lib/seo/business-info";
import { SERVICE_SLUGS } from "@/lib/services";

/**
 * `/sitemap.xml` — generated by Next.js from this file at build time.
 *
 * Why this exists rather than a static XML:
 *  - The route list is derived from i18n locales × service slugs. Hand-maintaining
 *    the cartesian product is bug-bait — one stale entry and crawlers either
 *    miss a page or 404 on a removed one. Generating from the same constants
 *    that drive the routes themselves keeps the sitemap honest.
 *  - Per-URL `alternates.languages` (hreflang) lets Google/Bing serve the
 *    correct locale to the right audience. The site is bilingual EN/ES for a
 *    South Florida market — skipping hreflang would split signal across two
 *    URLs that compete with each other.
 *
 * Conventions:
 *  - One entry per (locale, path). Each entry advertises every locale variant
 *    under `alternates.languages`, plus `x-default` pointing at the EN URL
 *    (matches `routing.defaultLocale === "en"`).
 *  - `lastModified` is `new Date()` at request time — fine for a marketing
 *    site with no per-page editorial history yet. When real content lands we
 *    can wire this to file mtime or a CMS timestamp.
 *  - `changeFrequency` and `priority` are advisory (search engines mostly
 *    ignore them in 2024+), but we set sane values so the XML is well-formed
 *    and so any tool that does respect them gets useful hints.
 */

type StaticPath = {
  /** Path under the locale prefix. "" means the locale root (homepage). */
  path: string;
  changeFrequency: NonNullable<MetadataRoute.Sitemap[number]["changeFrequency"]>;
  priority: number;
};

/**
 * Static (non-parameterised) routes that exist under `app/[locale]/`. Keep
 * this list aligned with the filesystem — if a route is added/removed in
 * `app/[locale]/`, mirror it here. Routes that don't yet have a built page
 * (e.g. `/about`) are deliberately omitted to avoid sitemap-listed 404s.
 */
const STATIC_PATHS: readonly StaticPath[] = [
  { path: "", changeFrequency: "weekly", priority: 1.0 },
  { path: "/services", changeFrequency: "monthly", priority: 0.9 },
  { path: "/about", changeFrequency: "monthly", priority: 0.7 },
  { path: "/contact", changeFrequency: "yearly", priority: 0.7 },
] as const;

/** Per-service detail pages under `/services/[slug]`. */
const SERVICE_PATHS: readonly StaticPath[] = SERVICE_SLUGS.map((slug) => ({
  path: `/services/${slug}`,
  changeFrequency: "monthly" as const,
  priority: 0.8,
}));

const LOCALES = routing.locales as readonly Locale[];
const DEFAULT_LOCALE = routing.defaultLocale;

/** Build the absolute URL for a (locale, path) pair. */
function urlFor(locale: Locale, path: string): string {
  return `${SITE_URL}/${locale}${path}`;
}

/**
 * Build the `alternates.languages` map for a given path. Includes every
 * supported locale (self-reference is intentional — Google treats it as
 * valid and makes the inheritance explicit) plus an `x-default` entry that
 * points at the default-locale URL.
 */
function alternatesFor(path: string): Record<string, string> {
  const languages: Record<string, string> = Object.fromEntries(
    LOCALES.map((l) => [l, urlFor(l, path)]),
  );
  languages["x-default"] = urlFor(DEFAULT_LOCALE, path);
  return languages;
}

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  const allPaths: readonly StaticPath[] = [...STATIC_PATHS, ...SERVICE_PATHS];

  // Cartesian product: every path × every locale. Emitting one entry per
  // locale (rather than collapsing locales into a single entry via alternates
  // only) is the form Google's sitemap docs recommend for hreflang-rich sites.
  return allPaths.flatMap(({ path, changeFrequency, priority }) =>
    LOCALES.map((locale) => ({
      url: urlFor(locale, path),
      lastModified,
      changeFrequency,
      priority,
      alternates: {
        languages: alternatesFor(path),
      },
    })),
  );
}
