import { existsSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { isConsolidatedPath } from "@/lib/consolidation";
import { languageAlternates } from "@/lib/spanish-site";

/**
 * Google ignores non-reciprocal hreflang, so a pair that only one side declares
 * does nothing at all. This file exists because that failed twice:
 *
 * - first when the Spanish builder special-cased one slug and emitted
 *   `{ "es-US": self }` for every other page;
 * - then again when 36 of 103 Spanish routes shipped with no entry in this map
 *   at all, so the `?? { "es-US": path }` fallback made them self-referencing.
 *   Measured 2026-10-06 against the served HTML, not against this map.
 *
 * The consequence is not cosmetic: with the Spanish page unpaired, Google
 * ranked the ENGLISH page at 15.0 for the Spanish query "editor de reels fort
 * lauderdale" and the Spanish page did not appear at all.
 */
describe("hreflang map", () => {
  const entries = Object.entries(languageAlternates);

  it("declares both languages and an x-default on every entry", () => {
    for (const [path, langs] of entries) {
      expect(langs["en-US"], `${path} is missing en-US`).toBeTruthy();
      expect(langs["es-US"], `${path} is missing es-US`).toBeTruthy();
      expect(langs["x-default"], `${path} is missing x-default`).toBeTruthy();
    }
  });

  it("is reciprocal: each side points at the other and is itself mapped", () => {
    for (const [path, langs] of entries) {
      const en = langs["en-US"];
      const es = langs["es-US"];
      expect(path === en || path === es, `${path} maps to a pair it is not part of`).toBe(true);
      // The counterpart must carry an identical mapping, or Google drops both.
      for (const other of [en, es]) {
        expect(languageAlternates[other], `${other} is not in the map, so ${path} is one-way`).toBeDefined();
        expect(languageAlternates[other]["en-US"]).toBe(en);
        expect(languageAlternates[other]["es-US"]).toBe(es);
      }
    }
  });

  it("never points two different Spanish pages at one English page", () => {
    // A double claim tells Google two unrelated pages are the same translation.
    // An automated fuzzy match produced exactly this, mapping the lawyer,
    // dentist, gym, medspa and contractor pages all onto the automotive page.
    const claimed = new Map<string, string>();
    for (const langs of Object.values(languageAlternates)) {
      const en = langs["en-US"];
      const es = langs["es-US"];
      const prior = claimed.get(en);
      expect(prior === undefined || prior === es, `${en} is claimed by both ${prior} and ${es}`).toBe(true);
      claimed.set(en, es);
    }
  });

  it("points x-default at the English page", () => {
    for (const [path, langs] of entries) {
      expect(langs["x-default"], `${path} x-default should be the en-US URL`).toBe(langs["en-US"]);
    }
  });

  it("only maps paths that are real routes on disk", () => {
    // The reciprocity assertions above all PASS on a mapping that points at a
    // slug which does not exist: sabotaging one entry still leaves the map
    // internally consistent. Verified by negative control 2026-10-06 — the
    // guard went green on a deliberately broken pair until this test existed.
    // Route existence is the property that actually breaks hreflang.
    const root = path.resolve(__dirname, "..", "..", "app");

    // Paths generated by a dynamic segment via generateStaticParams. Only these
    // parents may contain a route with no literal directory.
    //
    // This allowlist is deliberately narrow. A previous version accepted ANY
    // path whose parent merely contained some `[param]` directory, and because
    // `app/(spanish)/es` holds a catch-all, that made every `/es/<anything>`
    // look valid — the negative control went green on a slug that did not
    // exist. Verified by sabotage both before and after.
    const generatedParents = new Set([
      "/case-studies",
      "/guides",
      "/portfolio",
      "/es/casos-de-estudio",
      "/es/guias",
      "/es/portafolio",
    ]);

    const routeExists = (p: string) => {
      const group = p.startsWith("/es") ? "(spanish)" : "(english)";
      if (existsSync(path.join(root, group, p === "/" ? "" : p, "page.tsx"))) return true;
      return generatedParents.has(path.posix.dirname(p));
    };

    const missing: string[] = [];
    for (const langs of Object.values(languageAlternates)) {
      for (const target of [langs["en-US"], langs["es-US"]]) {
        if (!routeExists(target)) missing.push(target);
      }
    }
    expect([...new Set(missing)], "hreflang points at routes that do not exist").toEqual([]);
  });

  it("never pairs a consolidated page", () => {
    // A page merged or noindexed by the 2026-08-12 cohort decision is kept out
    // of the sitemap on purpose. Advertising an hreflang pair for it tells
    // Google to index something we have asked Google not to index.
    //
    // Ten proposed pairs were caught by this on 2026-10-06, after the sitemap
    // test went red — they were all consolidated on both sides.
    const offenders: string[] = [];
    for (const [path, langs] of Object.entries(languageAlternates)) {
      for (const target of [langs["en-US"], langs["es-US"]]) {
        if (isConsolidatedPath(target)) offenders.push(`${path} -> ${target}`);
      }
    }
    expect(offenders, "hreflang advertises consolidated pages").toEqual([]);
  });
});
